export const data = [
  {
    id: 1,
    userName: 'johndoe',
    link: 'https://images.pexels.com/photos/3039036/pexels-photo-3039036.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    likes: 0,
    comments: 0,
    shares: 0,
    profilePic:
      'https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    time: '2h',
    description: 'This is my first post',
    liked: false,
    bookmarked: false,
    replies: [],
    repliesCount: 0,
    type: 'p',
  },
  {
    id: 2,
    userName: 'Simon Hill',
    link: 'https://images.pexels.com/photos/5593106/pexels-photo-5593106.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    likes: 10,
    comments: 0,
    shares: 2,
    profilePic:
      'https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    time: '2h',
    description: 'This is my first post',
    liked: false,
    bookmarked: false,
    replies: [],
    repliesCount: 0,
    type: 'p',
  },
  //   {
  //     id: 3,
  //     userName: 'johndoe',
  //     link: 'https://cdn.pixabay.com/video/2020/01/05/30902-383991325_large.mp4',
  //     likes: 1000,
  //     comments: 80,
  //     shares: 50,
  //     profilePic:
  //       'https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  //     time: '12h',
  //     description: 'This is my first reels video',
  //     liked: false,
  //     bookmarked: false,
  //     replies: [],
  //     repliesCount: 0,
  //     type: 'reel',
  //   },
  {
    id: 4,
    userName: 'johndoe',
    link: 'https://images.pexels.com/photos/3039036/pexels-photo-3039036.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    likes: 0,
    comments: 0,
    shares: 0,
    profilePic:
      'https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    time: '2h',
    description: 'This is my first post',
    liked: false,
    bookmarked: false,
    replies: [],
    repliesCount: 0,
    type: 'p',
  },
];
